jupyterhub/batchspawner

batchspawner/batchspawner.py
This adds a preliminary support for Sun/Oracle Gridengine batch system. Tested with `OGS/GE 2011.11p1`.
=> Adding Sun/Oracle Gridengine spawner

batchspawner/batchspawner.py
I added `{partition}` and `{qos}` values for Slurm templates
=> Slurm partition qos

README.md
Updating the markdown spacing so the README will parse correctly in a prototype documentation project.
=> Edit README title spacing

batchspawner/batchspawner.py
In the jupyterhub terminal when using CondorSpawner under Debian, /bin/sh was always being used rather than the user's login shell, because the SHELL environment variable was not set.
UserEnvMixin had to be updated to work with modern versions of the jupyterhub spawner that expect derived classes to override get_env().
=> Use the correct shell in jupyterhub terminal under CondorSpawner

batchspawner/batchspawner.py
The batch script is the same as TorqueSpawner, only the commands and the regex changes.
=> Add MoabSpawner based on TorqueSpawner

batchspawner/batchspawner.py
Subclassed BatchSpawnerBase to create a new spawner for LSF.
=> Added LsfSpawner for IBM LSF

batchspawner/batchspawner.py
=> New traitlets api

batchspawner/batchspawner.py
Add ngpus as a configurable item, as per nprocs.
=> Add ngpus as an option to pass to the RMS

batchspawner/batchspawner.py
Hi there!
I just had a terrible time trying to debug what was going on with this spawner, so I've added some error handling to improve the response to the user if something's wrong. This also logs raw to logging.error, allowing for easier debugging at setup.
=> Add error logging for commands.

README.md
This changelog includes changes going back one year only.  It includes two more changes for which I have PRs since they are not major changes, but they can also be removed if they aren't accepted.
It could use advice on upgrading, but I don't see any breaking changes.
Feel free to just copy this info to a different file and close the PR, too.
=> Add a changelog to bottom of README.md

batchspawner/batchspawner.py
=> run_command: Increase debugging output in case of error

.travis.yml
Closes #110 
Supersedes PR #115
=> Fix attrs/jsonschema breakage

batchspawner/batchspawner.py
This change got lost in my previous mess of branches.  Based on previous review feedback.
---
- Thanks @willingc
=> Update req_srun help string

SPAWNERS.md
- A more proactive attempt to get more eyes and community.
=> Add note on spawner maintainers

README.md
Fixes documentation for remote port selection.
- Closes: #126
=> Add documentation of #58, selecting the port on the remote side

README.md
- This adds a debugging hints section.  Debugging isn't that hard if
you know where to look and in what order.
- Please suggest more hints that should be added here
=> README.md: Add some debugging hints

batchspawner/batchspawner.py
- A warning was raised that we used the wrong method to warn.
=> log.warn -> log.warning

README.md
Suggested update to wrapspawner example config based on issues https://github.com/jupyterhub/wrapspawner/issues/35 and https://github.com/jupyterhub/wrapspawner/issues/36.
=> Wrapper config fix

.travis.yml
This will attempt various things to fix CI (and perhaps update latest
versions tested).
=> travis: Attempt to fix CI

CONTRIBUTING.md
=> CONTRIBUTING: Fix contributor guide URL

.github/workflows/test.yaml, pyproject.toml
Just a small contribution to add python 3.12 for tests.
=> Add python 3.12 for tests

batchspawner/batchspawner.py
Credit to [NPotvin](https://github.com/NPotvin)
closes #281
=> allow for req_keepvars_extra to be configured
