jupyterhub/batchspawner

batchspawner/batchspawner.py
This allows to provide any submit script options not covered by common traits. `GridengineSpawner` is switched to use the trait instead of the options form, which is not available anyway when wrapped into
`ProfilesSpawner`. I have also made Torque and SLURM spawners to use the trait; I hope that's ok.
As a side note, the `ProfilesSpawner` works great! I like how it allows to preconfigure common spawner types. Here is configuration example I used with SGE:
```py
c.JupyterHub.spawner_class = 'batchspawner.ProfilesSpawner'
c.ProfilesSpawner.profiles = [
( "SGE Job - 1 GPU", 'sge_1gpu', 'batchspawner.GridengineSpawner', dict(req_options='-l gpu=1') ),
( "SGE Job - 2 GPU", 'sge_2gpu', 'batchspawner.GridengineSpawner', dict(req_options='-l gpu=2') ),
( "SGE Job - 3 GPU", 'sge_3gpu', …
```
=> Add req_options trait to BatchSpawnerBase class

batchspawner/batchspawner.py
self.env is deprecated in JupyterHub releases 0.6.0 onwards. Prior to this commit the batch script would fail because the keepvars variable was empty. The get_env method didn't appear until the JupyterHub 0.4.0 release, so this commit will break compatibility with versions prior to 0.4.0."
=> Use self.get_env() rather than self.env in class BatchSpawnerBase.

batchspawner/batchspawner.py
The packaged templates use hardcoded `/home/{user}/` paths, but that's not necessarily the correct value for the user's home directory. I've added `{homedir}` for use in templates.
=> Support homedir value for script template

.gitignore, .travis.yml, batchspawner/batchspawner.py, batchspawner/tests/conftest.py, batchspawner/tests/test_spawners.py
Note this is still a first pass at implementing testing -- only the core functionality of the batchspawner base class is exercised. Integration tests for the WrapSpawner are still needed, since that is probably more sensitive to small changes in the interaction between the Hub and Spawner.
=> Add tests and travis-ci testing

README.md, batchspawner/batchspawner.py
One thing that could be improved with this initial support for condor is that if req_nprocs or req_memory are not configured, job submission fails, because the statements defining RequestMemory and RequestCpus are malformed.  It would be nice to omit these statements if the corresponding variable is empty or provide reasonable defaults.
Does this problem affect the other batch systems as well?  If so, perhaps we can have a common solution.
=> Add support for the HTCondor batch system.

batchspawner/batchspawner.py
When slurm has been compiled with --enable-multiple-slurmd, the administrator sets the name of the slurmd instance via the slurmd -N option. This node name is usually different from the hostname and may not be resolvable by JupyterHub. Here we enable the administrator to map the node names onto the real hostnames via a traitlet.
=> Add MultiSlurmSpawner.

batchspawner/batchspawner.py
Since Jupyterhub 0.7, start method should "Return ip, port instead of setting on self.user.server directly." [1].
[1] https://github.com/jupyterhub/jupyterhub/blob/d44ee4b8fa45cde12c764fffd34ff17ad34c590e/jupyterhub/spawner.py#L519
=> Add return statement to BatchSpawner.start

batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
In particular, (synchronous) `subprocess` not needed if using Tornado's async alternative.
=> Remove superfluous imports

batchspawner/batchspawner.py
In Jupyterhub 0.7, the preferred method of setting the port for the user
server became to set it on self.port instead of self.user.server.port
directly.
This commit changes setting self.user.server.[ip|port] to
self.[ip|port]. It also has backwards compatability for 0.7
=> Fix the user.server warning when setting port

batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
Fixes the batchspawner and the tests to work with Jupyterhub 0.8
In particular:
* `self.user.server` is no longer a thing, ip and port is stored on `self.ip` and `self.port`
* The hub now uses `0.0.0.0` as the default IP address
=> 0.8 updates

batchspawner/batchspawner.py
Simple pull request to launch jupyter jobs on different Slurm clusters. The configuration can all be completed with `jupyterhub_config.py`.
When dealing with clusters, these lines break `state_ispending` & `state_isrunning`:
```python
state_pending_re = Unicode(r'^(?:PENDING|CONFIGURING)').tag(config=True)
state_running_re = Unicode(r'^(?:RUNNING|COMPLETING)').tag(config=True)
```
The beginning of line character breaks clusters capability because queries print a leading line. Is this there for a reason? It can probably be safely removed.
```python
c.SlurmSpawner.batch_query_cmd = 'sudo -E -u {username} squeue -M {cluster} -h -j {job_id} -o "%T %B"'
c.SlurmSpawner.batch_cancel_cmd = 'sudo -E -u {username} scancel -M {cluster} {job_id}'
c.SlurmSpawner.state_pending_re = …
```
=> Allow for the ability to launch on multiple Slurm clusters

batchspawner/batchspawner.py
otherwise the `user_options` dictionary is nested inside the `subvars["user_options"]` value and cannot be used easily in the batch script
=> merge user_options dict with subvars

.travis.yml
To get the tests working, we need to conditionally pin the tornado version. Specifically we conditionally install tornado before the jupyterhub dev-requirements.txt file is processed. The reason is that by default we will pull in tornado 5.0, which breaks the testing because
- it cannot be installed on Python 3.3
- the jupyterhub test suite is broken on tornado 5.0 for the released versions (currently through 0.8.1)
This branch lets Jupyterhub pull in the default tornado version for the master branch (allowed to fail) but otherwise uses 4.1<ver<5.0. We also bump the newest tested jupyterhub release to 0.8.1.
=> Fix testing versions

batchspawner/batchspawner.py
Import subprocess for CalledProcess error and remove references to
self.log, not defined outside Spawner classes.
=> Fix exception handling in run_command

batchspawner/batchspawner.py
This change was needed for our cluster which was just upgraded to slurm 17.11.5: without it, we get `Error: sbatch: error: --uid only permitted by root user`.  Since we use sudo to run sbatch, it seems that an explicit `--uid` option is not needed.  This would be needed if we supported submitting as an admin user and slurm handles the user changing - but it seems sudo is probably the better option.  Thoughts?
Commit comment:
- The --uid option is not allowed for non-root users anymore in Slurm17.11.5 (at least)...
- Since we submit using sudo, this option seems to be no longer needed.
=> slurm: remove --uid option (redundant with sudo)

README.md, batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py, version.py
Merge release branch for 0.8.1
v0.8.1 (bugfix release)
* Fix regression: single-user server binding address is overwritten by previous session server address, resulting in failure to start.  Issue #76
=> Release 0.8.1

.travis.yml
Add jupyterhub 0.9.0b2 to travis.yml, but will need updating as jupyterhub beta releases progress.
Closes: #78.  See also discussion there about simplifying the matrix.
=> Test with jupyterhub 0.9

.travis.yml
- Mirrors the latest requirements of JupyterHub.
- Discussion in #78.
I'm not necessarily saying that this is a good idea. From #78:
I tend to think that HPC is rather conservative and slow to upgrade, so my inclination is to support backwards compatibility a lot. But, JupyterHub is changing so fast it probably doesn't make sense to use anything older than 0.8.1 anyway.
If it was up to me, I would say "yes" for the main reason that I'm not going to be able to support older versions very well since I have only recently started here.  If we don't do this, can someone help with older versions?
Thoughts?
=> .travis.yml: Require JupyterHub>0.8.1 and Python>3.5

README.md, batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py, requirements.txt
I have created my own integration branch for #66 #73 #74 and #72.  Unfortunately, individual pull requests have taken too long and essentially paused the development of batchspawner for university for a while, so I took the initiative to make my own integration branch and start collecting things together and testing them.
In general, is there any better way to handle jupyterhub development?  A better way to communicate, better way to get fast feedback?  I'd also prefer individual PRs, but haven't gotten any comments on them, so I can't be easily granular.
So far, I've added tests that cover #72, #73, and #66 somewhat.
The whole thing works with JupyterHub 0.9 + SlurmSpawner for me in basic testing.  I will continue internal testing and update this PR with comments when I do more.
=> Integration of run_command, exec_prefix, slurm script, and jinja2

README.md, batchspawner/batchspawner.py, requirements.txt
Initial attempt at jinja2 templates.  Backwards compatible and works for me, but needs documentation and a bit more before finalizing.  Is this wanted?
- If the batch_script or any other string has {{ or {% in it, treat it
as a jinja2 template and do advanced formatting.
- Allows for optional options to be more easily supported.
- Initial implementation for SlurmSpawner only.
Also solves #64.
=> Basic implementation of jinja2 templating

batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
- This adds the option exec_prefix which can be used for overriding
the sudo command to use when manipulating jobs.
- This defaults to "sudo -E -u {username}" and is appended to every
command before it is run.
- The condor_q command did not have sudo, but likely can be used here.
- Closes: #39 
Missing and very important: tests to ensure that exec_prefix is actually used.  But please pull #72 first since that will make things easier to test.
=> Add exec_prefix option

README.md, batchspawner/batchspawner.py, requirements.txt
This PR is necessarily based on #66 (jinja2 templating).  That one should be pulled first, then this diff will make sense.
- By using `srun` for cmd, slurm will properly signal shutdown with
SIGTERM in advance.  Closes: #50
- Add prologue and epilogue options in case other setup is needed
before or after the script runs (e.g. `unset XDG_RUNTIME_DIR`).
- Some other script nicesess.
- This will eventually need porting to the other spawners, but will
require some local knowledge.  Slurm first, then others.
=> Updates to slurm script: proper termination and generalization

batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
- Clarify the batch process error message.  Previously, this was an
AssertionError, whose text was presented to the user in a very
confusing fashion.
Related: jupyterhub/jupyterhub#1915
=> Clarify confusing AssertionError when pending batch process disappears

batchspawner/batchspawner.py
- To properly run in slurm, one is supposed to use "srun" for each job
step (though this isn't required).  dff4482 added the srun, but this
has some side-effects, mainly (for me at least) that environment is
*actually* handled the way it should be.  But this broke some
functionality that depended on environment.  Since this caused
problems, and may cause problems for others, "srun" should be made
optional.  This does that.
- The root problem is that the batch script reads .bashrc /
.bash_profile, but when the notebook server is run using 'srun', it
clears these environment variables and uses only the keepvars
setting.  (Of course, this itself is a security risk and the initial
purpose of limiting the environment).
- To disable srun, set SlurmSpawner.req_srun=''.
- If, upon upgrading, your …
=> SlurmSpawner: make "srun" optional

.travis.yml, README.md, SPAWNERS.md, batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
I started this as integration branch of all patches for next release.  Not everything is here yet, but I will try to integrate on here.  Feedback from community about what to integrate is welcome.
I will use #103 to list what is integrated into this already.
Runs OK on my dev instance.  Let's see if tests pass.
=> Integration branch for next release

batchspawner/batchspawner.py
Hi there,
I know for certain that Slurm can take a full text reservation name - perhaps the other schedulers can use this. But having this optional flag is nice for busier clusters.
=> Add reservation option for Slurm

batchspawner/batchspawner.py
- It would be possible to have exec_prefix use string formatting and
the command itself use jinja2 formatting, and when combined the
string formatting would fail.  To handle this, template them
separately and then concatenate.
=> Update exec_prefix handling: template this separate from batch command.

batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
- These options first appeared in dff4482 for SlurmSpawner
- Add tests for this option
- Not currently implemented for CondorSpawner, since it uses a
different method using `bash -c`.  It could be added there, but
someone with local knowledge should do that.
=> Add prologue and epilogue options to other spawners

README.md, SPAWNERS.md
This creates a separate page to list specific spawner information, and eventually design considerations (security, graceful termination) for spawners.  It can be used so that each specific spawner maintainer can ensure that their spawner meets all important requirements.
Another idea here is "spawner maintainers", since not everyone can know about all of them.  The idea is that we can keep track of who knows about which, and ping them when necessary.
Any comments on these notes, anything to add?
=> [WIP] Add SPAWNERS.md, a list of specific info on spawners

batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
This is part of my project to make batchspawner handle the user environment better.  It doesn't immediately make things better, but provides one tool which will help environment management later.
The `req_keepvars` defaults to a lot of stuff from inside JupyterHub.  If you want to add something, you have to copy and paste the default - something fragile.  This lets you append without worrying about what is inside.
---
Add keepvars_extra to whitelist more environment.
- Existing keepvars will whitelist environment variables, but is
all-or-nothing: you can't append to existing required environemnt
variables that JupyterHub requires.
- This allows a comma separated list of the same format as
req_keepvars that gets appended to keepvars, with one extra comma
between them.
=> Keepvars extra

batchspawner/batchspawner.py
I was just looking at the code so introduced some minor changes for consistency (within, with PEP-8, and with jupyterhub).  Feel free to ignore/discard.
=> Miscellaneous minor tune ups, shouldn't effect functioning 

batchspawner/batchspawner.py
- Reading from stdout and stderr separately can produce a deadlock.  I
assume that the separate proc.wait_for_exit() doesn't matter here.
- Thanks to @krinsman in #90.
=> run_command: Fix possible deadlock

batchspawner/batchspawner.py
See discussion in #108.  I'm not entirely sure this PR is needed.  I'd rather at least one person say "yes, this would help me" and close otherwise.
---
- Previously, only the query command got the full enivornment.
- If this is used to authenticate to the submit/query/cancel commands,
then the user's environment gets this also.
- Closes: #108
=> Pass the environment dict to all commands (query and cancel)

batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
For PBS versions above > 13.X.
Closes #79 
It works on my environment with the following config:
````python
c.BatchSpawnerBase.req_prologue = 'module load conda; source activate jupyterhub'
c.BatchSpawnerBase.exec_prefix = 'sudo -E -u {username} env PATH=$PATH'
````
First line for loading correct env for the user. Second line because the PATH does not contain qsub and other PBS methods when sudoing.
=> Adding PBSSpawner

.travis.yml
jsonschema 3.0 requires attrs 17.4, but pip doesn’t seem to pull it in
closes #110
=> pin attrs for jsonschema

batchspawner/__init__.py, batchspawner/api.py, batchspawner/batchspawner.py, batchspawner/singleuser.py, batchspawner/tests/test_spawners.py, scripts/batchspawner-singleuser, setup.py
**Context**
We provide compute nodes on our GPU cluster for a graduate deep learning course through JupyterHub and BatchSpawner. The nodes are available two hours a week under a reservation for the course (a lab period). Each node has 8 GPUs, a student is allocated one GPU and there are around 30 students running Notebook at the same time. Therefore, multiple jupyterhub-singleserver can run on a single compute node. Until last week, it was working flawlessly.
**Problem**
During last week lab period, two users reported being unable to connect to their notebook. After inspecting their notebook log, I found this message:
> [I 2018-02-16 10:26:57.826 SingleUserNotebookApp notebookapp:1191] The port 58824 is already in use, trying another port.
> [C 2018-02-16 10:26:57.826 …
=> Select singleserver port number on remote host

.travis.yml
- As agreed during Jupyterhub for research facilities sprint.
- For now, test PR to see what works on Travis currently.
=> Drop backwards compatibility to jupyterhub==0.9.6 and python==3.5

batchspawner/api.py, batchspawner/batchspawner.py
Combined with jupyterhub/wrapspawner#27, it solves the issue mentioned in #103, #127 and #132.
It also paves the way to support named servers by generalizing the batchspawner api.
=> Replace current_ip and current_port by ip and port

batchspawner/batchspawner.py, batchspawner/singleuser.py
Instead of creating a batchspawner notebook app, batchspawner-singleuser
is now a wrapper that finds a port and add the port number to the
command-line argument of the singleuser app. This allows the usage
of batchspawner with jupyterlab for example.
=> Allow batchspawner to be used with different notebook singleuser cmd

.travis.yml, README.md, batchspawner/api.py, batchspawner/batchspawner.py
This is an integration branch made to test if the most important other
PRs work together, while waiting for others to go in.  However it can
be seen as a line of development, too.
All of these PRs do work together, it seems, with only minor fixups.
This could use testing on other clusters.
- #140: JH1.0 compatibility, most others wait for this.
- #130: minor documentation
- #90: refactor to use Python 3.5 asyncio
- #86: JH0.9 progress indicators
Closes: #143, #141, #139, #133, #130, #90, #86 (PRs)
Closes: #131, #126 (Issues) at least.
=> Integration: #143 (inc. #141, #139), #130, #86, #90

.travis.yml, batchspawner/batchspawner.py, requirements.txt
This was my attempt at adding progress indicators for JupyterHub 0.9 ( jupyterhub/jupyterhub#1771), #81 of batchspawner.  However, it just doesn't work.  In fact, I find no indication it is even using this .progress method at all, which makes me think there is something fundamentally wrong with what I am doing (if I put an exception in it, it doesn't raise it... it always uses the base Spawner .progress method.).
There is some junk in here still: it's artificially slowing down to make it last longer.  I've also tried to using async_generator instead of gen.coroutine.  It also doesn't do anything useful, since I was just trying to get *any* sign of it working first, but it can integrate with the spawner estimated start times and so on before this is ready to go.
Any ideas? Any known …
=> [WIP] Add progress indicators for jupyterhub 0.9

batchspawner/batchspawner.py
Apparently [(according to the Tornado wiki)](http://www.tornadoweb.org/en/stable/gen.html) `@gen.coroutine` has been deprecated by the Tornado project itself in favor of "native" coroutines implemented with the `asyncio` module, and as of Tornado v. 5.0, even `tornado` itself is written using `asyncio`, instead of `tornado.gen.coroutine`. Also most of the classes in the parent JupyterHub project are written using `asyncio` instead of `torndao.gen.coroutine`.
So it seemed to me like a possibly good idea if the coroutines in `batchspawner` were reimplemented using `asyncio` instead of `tornado.gen.coroutine`, to avoid problems with Tornado or JupyterHub possibly making breaking changes to the code in the future.
The documentation for the parent `Spawner` class in JupyterHub (if I remember …
=> Implementation of coroutines with asyncio (possibly shortens `run_command` substantially)

README.md, batchspawner/batchspawner.py
In addition, added a missing configuration option to README.md which took me two hours to debug
=> Workaround for Kerberos bug in slurm `sbatch --parsable` (solves #148)

batchspawner/tests/test_spawners.py
Tests were giving over 200 warnings - reduce that.
Tests: set 'mock_port' and 'server' explicitely
- Modern traitlets doesn't set arbitrary keyword arguments, and these
two attributes are not traitlets.  Thus, set them explicitely after
spawner creation.
- This may fail (server) on the jupyterhub < 0.8 branch, but that is
deprecated and I will likely remove it shortly.
Dont' set *_TIMEOUT on tests
- These are on LocalProcessSpawner, not Spawner, so do nothing here.
- These were also renamed to lowercase
- In short, these weren't used before
=> Fix test warnings

batchspawner/api.py, batchspawner/singleuser.py
Since [v0.8](https://jupyterhub.readthedocs.io/en/stable/changelog.html#id15), JupyterHub has supported "named servers."  If `c.JupyterHub.allow_named_servers=True` in the hub config, servers can have names assigned to them.  If this setting is `False` then there is only one server with the name '' (empty string).
For BatchSpawner to work with named servers, the port selected by `batchspawner-singleuser` must be routed to the right spawner.  Right now the port is attached to `user.spawner` but this is really just an alias for `user.spawners['']`.  Without this fix the port value lands on the empty-string spawner and that may not be what the user wanted to happen at all.
To tell the hub which spawner to attach the port information to, this PR has `batchspawner-singleuser` read the value of …
=> Support named servers

batchspawner/batchspawner.py
Bash generally keeps executing code line by line even
if any of the lines fail. For example, if your path is
not set properly, `batchspawner-singleuser` will not
be found by `which`. This should terminate execution.
However, without `set -e`, execution will just continue
and fail with a different error.
This patch does `set -euo pipefail` for all submission
scripts. This causes them to fail on:
1. Any non-zero command return code (-e)
2. On undefined environment variables (-u)
3. Treat failures in any part of a pipeline as failure,
rather than just the last command (-o pipefail)
=> Fail hard on first error in batch script

CHANGELOG.md, batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
As the name tells, it allows to specify e.g. GPU requests
=> add 'gres' option to SlurmSpawner

batchspawner/batchspawner.py
Switched --workdir in the slurm section to be --chdir instead. Slurm 19.05 series removed the --workdir option.
=> Update batchspawner.py to use --chdir instead of --workdir

batchspawner/batchspawner.py
When running as a service, the path for qsub/qstat/qdel commands is needed in the environment. In addition, several SGE environment variables are needed in order to submit jobs to the cluster. These are mentioned in the SGE install guides and are carried over to Univa Grid Engine as well. 
Here's an older [admin guide (page 7)](http://www.univa.com/resources/files/univa_admin_guide_univa_grid_engine_854.pdf#page=7) describing the variables
Tested with UGE-8.6.4
=> Grab environment variables needed for grid engine

batchspawner/batchspawner.py
- `-o pipefail` is a bashism, so that the spawner scripts that use
`/bin/sh` can't possibly work if it's not linked to bash.  As a
immediate workaround, remove the option on the non-bash scripts.  A
long-term plan will come later.
- Closes: #184, Discussion: #184
- Fixes up: #177
- Follow-up in: #188
=> batchspawner/batchspawner: Don't use `-o pipefail` in /bin/sh scripts

batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
- As mentioned there, I am following up in a new PR since I don't know
if I should edit that one.
- Remaining suggestions from there are applied
- Make tests pass, the key commit is
https://github.com/rkdarst/batchspawner/commit/c81298d8acd67550a9bdeaed547c6e45dda2254f
(which I'd recommend that people review if they want to review anything)
- Add further tests for the unknown job state.
- Closes: #179, #178, #174, #171
- This took a lot of work and hand-drawn diagrams to understand the
exact spawning process, but I think I got it and it matches the
behavior expected by JupyterHub.  But I encourage anyone with deeper
wisdom to take a look.
=> unknown job state: Improvements of #179 to make tests pass

MANIFEST.in
Closes #197 
Tested with `python setup.py sdist`, and then building from source in `dist/`. It worked after I added both `version.py` and `requirements.txt` to `MANIFEST`.
Tested too that `python setup.py bdist_wheel` did not include these files.
=> Include version.py and requirements.txt in MANIFEST for sdist

batchspawner/batchspawner.py
The exception handling in run_command had several issues
which this commit fixes:
- Don't use undefined variable.
- communicate() may block forever if process already
closed the pipes.
- exceptions during exception handling were not handled.
=> batchspawner/batchspawner: Fix exception handling in run_command.

.pre-commit-config.yaml
- noticed on #237
- this version is compatible with the unmanaged transient dependencies (click, etc) that pre-commit brings along
=> bump pre-commit black to stable

batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py, requirements.txt, setup.py
Considering batchspawner now requires jupyterhub >= 0.9, this PR removes code that ran only for JH < 0.9.
This PR also removes imports that are no longer used and bumped requirements in requirements.txt and setup.py.
=> Remove code no longer used

.github/workflows/test.yml, README.md, batchspawner/tests/conftest.py
We had CI test failures, they are resolved by this PR.
=> ci: fix broken tests by not installing pre-releases of jh's dev-requirements.txt

.github/workflows/python-publish.yml, .github/workflows/test.yml
This PR is solely about aligning the GitHub workflows with various practices across the JupyterHub org as they have evolved.
The test failures are unrelated and fixed in #241.
=> ci: tweaks to align with modern practices and jupyterhub org in general

scripts/batchspawner-singleuser, setup.py
- fixes #235
- this generally generates better/more secure scripts that are more predictable for downstream packagers e.g. debian, conda-forge
- also more cross-platform-compatible, which is a story for another day...
=> Replace use of scripts with entry_points

batchspawner/batchspawner.py
Bug description
I believe old LSF implementations used space node names where a job was submitted to multiple machines. bjobs now returns a host multiple times, seperated by a ':' if more than one slot is used on a node. This means the state_gethost no longer works on LSF when using more than one cpu.
Expected behaviour
Using more than one slot should work.
Actual behaviour
Using more than one slot does not work.
How to reproduce
Have an LSF 10.1 cluster and try and use LSF with more than one slot.
Your personal set up
LSF 10.1 on ubuntu 18.04
https://github.com/jupyterhub/batchspawner/issues/228
=> LSF jobs with multiple slots display each hostname ':' separated

.pre-commit-config.yaml, batchspawner/singleuser.py
I upgraded a development hub to jupyterhub 3.0.0b1 from 1.5.x and ran into a couple of issues. I'm using slurm and these issues were present with the latest release and latest in git:
Initially I was seeing the following warning:
```
/usr/local/linux/anaconda3.8/envs/jupyterhub-3.0/lib/python3.8/site-packages/batchspawner/singleuser.py:16: RuntimeWarning: coroutine 'HubAuth._api_request' was never awaited
hub_auth._api_request(method='POST',
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[I 2022-08-19 23:32:20.510 SingleUserLabApp mixins:610] Starting jupyterhub single-user server version 3.0.0b1
...
```
It did start the server, however the hub wouldn't redirect me to it.
This patch quells the warning, but more importantly causes hub to redirect me to the server …
=> Quell async warning, and POST with body for jupyterhub 3.0

README.md
There is a very insidious bug in the currently released version on PyPI (1.2.0) which causes things to break on newer JupyterHub instances without any errors or warnings. Adding a simple warning to the README will warn users about how to proceed, until 1.3.0 is released.
=> Add information about bug with JupyterHub 3+

batchspawner/tests/test_spawners.py
mock getpwnam to always return result for current user
since test user may well not exist on the system
In particular, JupyterHub 5 test utilities no longer create a test user with the running user's name, which is causing tests to fail, since so far batchspawner tests have assumed that the first user in the database matches `getpass.getuser()`.
=> TST: don't assume test user is OS user

batchspawner/tests/test_spawners.py
This PR fixes the regular expressions used to validate the submitted batch script.
Indeed according to [re.X](https://docs.python.org/3.10/library/re.html#re.VERBOSE) documentation:
> When a line contains a # that is not in a character class and is not preceded by an unescaped backslash, all characters from the leftmost such # through the end of the line are ignored.
So all regular expressions were matching to the line start.
=> Fix Slurm test used regular expression

batchspawner/batchspawner.py
=> Remove `which jupyterhub-singleuser` command from `SlurmSpawner.batch_script`

batchspawner/singleuser.py
Since JupyterHub 1.1.0, the HubAuth SSL attribute values are read from the same environment variables.
It was introduced by this PR:
https://github.com/jupyterhub/jupyterhub/pull/2588
This PR can wait until we drop batchspawner compatibility with JH < 1.1.0.
=> Remove reading/setting HubAuth SSL attributes in singeuser

batchspawner/batchspawner.py
Adds:
- logging of `subvars` (info)
- logging of `self.get_env` (debug)
Changes:
- the logging level of the submit script from `info` to `debug`. 
The rational is that it is easier to parse `subvars` dictionary in a separate log than the multiline submit script, which would then be only useful in a debug context.
Removes:
- `cmd` from the `Job submitted` info log, since it is was already logged before.
This PR also introduces the usage of logging argument instead of concatenating string with `+`.
I will follow with a second PR that standardize logging to use argument instead of string concatenation systematically.
=> Improve submit_batch_script logging

batchspawner/batchspawner.py, batchspawner/tests/test_spawners.py
Fixes #253 
Poll job status while waiting to get the port back from the single-server to catch any failure in the job before the server launches.
=> poll job status while waiting for single-user server to be reachable
